### ISSUE TITLE
Data Purchasing APIs (second iteration)

### ISSUE THREAD

**Issue by timoguin** [tiki/purchase#54]
# Description

Follow-up to the first iteration (#43) of the data purchasing APIs. Focused on implementing missing features and fixing any bugs.

# Issues

## Bugs

- [x] tiki/core-account-service#301

## Improvements

- [x] tiki/core-account-service#296
- [ ] https://github.com/tiki/core-account-service/issues/302
- [ ] https://github.com/tiki/core-account-service/issues/277
- [ ] tiki/core-account-service#303
- [x] https://github.com/tiki/core-account-service/issues/304
- [ ] https://github.com/tiki/core-account-service/issues/305
- [x] https://github.com/tiki/core-account-service/issues/306
- [x] https://github.com/tiki/core-account-service/issues/307
- [x] https://github.com/tiki/core-account-service/issues/308
- [ ] https://github.com/tiki/core/issues/7
- [ ] https://github.com/tiki/core-account-service/issues/309
- [ ] https://github.com/tiki/core-account-service/issues/311
- [ ] Standardize APIs - use explicit routes
